version: "3" # 사용하고자 하는 docker-compose 버전 명시(현재 최신 버전은 3.8)
services:
  postgresdb:
    image: postgres:latest
    container_name: postgresdb # 컨테이너 이름(docker dashboard에 뜨는 이름)
    restart: always # 항상 재시작(명시되어 있지 않을 경우 no가 default이며 어떤 상황에서도 restart 안함)
    ports:
      - "5432:5432" # HOST_PORT:CONTAINER_PORT로 host의 5432 포트를 container의 5432 포트와 매핑
    environment:
      POSTGRES_USER: postgres # 선택 속성으로 POSTGRES_PASSWORD와 함께 사용되며, POSTGRES_USER명으로 superuser가 생성됨(작성하지 않을 경우 postgres 이름으로 superuser 생성)
      POSTGRES_PASSWORD: 1234 # 필수 속성으로 postgreSQL의 superuser password(비어있거나 선언되지 않으면 안됨)
      POSTGRES_DB: springboot
  app:
    image: chanseller:latest
    container_name: chan
    restart: always # 항상 재시작(명시되어 있지 않을 경우 no가 default이며 어떤 상황에서도 restart 안함)
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb # db가 뜬 후에 app이 뜰 수 있도록 depends_on 설정
    environment: # springboot의 application-*.yml에 주입 필요한 정보
      PROFILE: "local"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/springboot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    links:
      - postgresdb
volumes:
  postgre-data: